# Site settings
title: My GitHub Pages Site
description: >-
  A description of your site for SEO and social sharing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://meadefish.github.io" # your GitHub Pages URL

# Build settings
markdown: kramdown
theme: minima # You can change this to any supported Jekyll theme

# Author settings
author:
  name: Meadefish
  email: your-email@example.com

# Plugins (add more as needed)
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude these files and folders from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Collections (optional)
collections:
  my_collection:
    output: true

# Defaults (optional)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Meadefish"

# Social (optional)
social_links:
  twitter: your_twitter_handle
  github: meadefish

# Pagination (optional)
paginate: 5
paginate_path: "/page:num/"

# Permalinks (optional)
permalink: pretty